/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package inventory;

import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.UnitValue;
import database.InventoryDB;
import java.io.FileNotFoundException;
import java.sql.*;
import java.util.Objects;
import javax.swing.JOptionPane;

/**
 *
 * @author indak
 */
public class FLaporanBarangKeluar extends javax.swing.JDialog {

    /**
     * Creates new form FLaporanBarangMasuk
     */
    public FLaporanBarangKeluar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbRentangWaktu = new javax.swing.JComboBox<>();
        btnCetak = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laporan Barang Keluar");

        jLabel1.setText("Rentang Waktu");

        cbRentangWaktu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hari Ini", "Kemarin", "Minggu Ini", "Bulan Ini", "Semua" }));
        cbRentangWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRentangWaktuActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCetak)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal))
                    .addComponent(cbRentangWaktu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbRentangWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetak)
                    .addComponent(btnBatal))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRentangWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRentangWaktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRentangWaktuActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        String rentangWaktu = Objects.toString(cbRentangWaktu.getSelectedItem(), "");
        String dest = "C:\\Users\\indak\\OneDrive\\Documents\\UNIPMA\\2023 GANJIL\\PRAKTIKUM PEMROGRAMAN BERORIENTASI OBYEK II (5D)\\UAS\\iText Report\\file.pdf";

        try {
            PdfDocument pdfDoc = new PdfDocument(new PdfWriter(dest));
            try (Document doc = new Document(pdfDoc, PageSize.A4.rotate())) {
                String header1 = "Laporan Data Barang Masuk";
                doc.add(new Paragraph(header1).setBold().setFontSize(16));
                String header2 = "Toko Gadget";
                doc.add(new Paragraph(header2).setFontSize(12));
                float[] colWidths = {5, 20, 20, 35, 20, 35};
                Table table = new Table(UnitValue.createPercentArray(colWidths)).useAllAvailableWidth();
                table.addHeaderCell(new Cell().add(new Paragraph("No").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("Kode Transaksi").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("Barang").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("Supplier").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("Jumlah").setBold()));
                table.addHeaderCell(new Cell().add(new Paragraph("Tanggal").setBold()));
                int i = 0;

                try {
                    Connection c = InventoryDB.getKoneksi();
                    String query = "SELECT t.code AS transaction_code, p.name AS product_name, s.name AS supplier_name, t.amount, t.date "
                            + "FROM transactions t "
                            + "LEFT JOIN products p ON t.product_id = p.id "
                            + "LEFT JOIN suppliers s ON t.supplier_id = s.id "
                            + "WHERE t.type = 'Out'";

                    if (rentangWaktu.equals("Hari Ini")) {
                        query += " AND DATE(t.date) = CURDATE()";
                    } else if (rentangWaktu.equals("Kemarin")) {
                        query += " AND DATE(t.date) = DATE_SUB(CURDATE(), INTERVAL 1 DAY)";
                    } else if (rentangWaktu.equals("Minggu Ini")) {
                        query += " AND DATE(t.date) BETWEEN DATE_SUB(CURDATE(), INTERVAL WEEKDAY(CURDATE()) DAY) AND CURDATE()";
                    } else if (rentangWaktu.equals("Bulan Ini")) {
                        query += " AND MONTH(t.date) = MONTH(CURDATE()) AND YEAR(t.date) = YEAR(CURDATE())";
                    }

                    PreparedStatement pstmt = c.prepareStatement(query);
                    ResultSet rs = pstmt.executeQuery();

                    while (rs.next()) {
                        table.addCell("" + (i += 1));
                        table.addCell(new Cell().add(new Paragraph(rs.getString("transaction_code"))));
                        table.addCell(new Cell().add(new Paragraph(rs.getString("product_name"))));
                        table.addCell(new Cell().add(new Paragraph(rs.getString("supplier_name"))));
                        table.addCell(new Cell().add(new Paragraph(rs.getString("amount"))));
                        table.addCell(new Cell().add(new Paragraph(rs.getString("date"))));
                    }

//                    rs.close();
//                    pstmt.close();
//                    c.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Error ambil data");
                    System.err.println(e);
                }
                doc.add(table);
                JOptionPane.showMessageDialog(this, "Sukses ekspor data: " + dest);
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error ekspor data");
            System.err.println(e);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLaporanBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLaporanBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLaporanBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLaporanBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FLaporanBarangKeluar dialog = new FLaporanBarangKeluar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetak;
    private javax.swing.JComboBox<String> cbRentangWaktu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
