/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory;

import javax.swing.JOptionPane;

/**
 *
 * @author indak
 */
public class FMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form FMenuUtama
     */
    public FMenuUtama() {
        initComponents();
        this.logout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnUser = new javax.swing.JMenu();
        mnLogin = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnKeluar = new javax.swing.JMenuItem();
        mnManajemenBarang = new javax.swing.JMenu();
        mnBarang = new javax.swing.JMenuItem();
        mnSupplier = new javax.swing.JMenuItem();
        mnPengadaan = new javax.swing.JMenu();
        mnBarangMasuk = new javax.swing.JMenuItem();
        mnBarangKeluar = new javax.swing.JMenuItem();
        mnLaporan = new javax.swing.JMenu();
        mnLaporanBarangMasuk = new javax.swing.JMenuItem();
        mnLaporanBarangKeluar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(449, 58));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG!");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Silakan Login Terlebih Dahulu");
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        mnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        mnUser.setText("User");

        mnLogin.setLabel("Login");
        mnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoginActionPerformed(evt);
            }
        });
        mnUser.add(mnLogin);

        mnLogout.setText("Logout");
        mnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLogoutActionPerformed(evt);
            }
        });
        mnUser.add(mnLogout);
        mnUser.add(jSeparator1);

        mnKeluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnKeluar.setText("Keluar");
        mnUser.add(mnKeluar);

        jMenuBar1.add(mnUser);

        mnManajemenBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings.png"))); // NOI18N
        mnManajemenBarang.setText("Manajemen Barang");

        mnBarang.setText("Data Barang");
        mnBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangActionPerformed(evt);
            }
        });
        mnManajemenBarang.add(mnBarang);

        mnSupplier.setText("Data Supplier");
        mnSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSupplierActionPerformed(evt);
            }
        });
        mnManajemenBarang.add(mnSupplier);

        jMenuBar1.add(mnManajemenBarang);

        mnPengadaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/truck.png"))); // NOI18N
        mnPengadaan.setText("Pengadaan");

        mnBarangMasuk.setText("Barang Masuk");
        mnBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangMasukActionPerformed(evt);
            }
        });
        mnPengadaan.add(mnBarangMasuk);

        mnBarangKeluar.setText("Barang Keluar");
        mnBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBarangKeluarActionPerformed(evt);
            }
        });
        mnPengadaan.add(mnBarangKeluar);

        jMenuBar1.add(mnPengadaan);

        mnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/report.png"))); // NOI18N
        mnLaporan.setText("Laporan");

        mnLaporanBarangMasuk.setText("Laporan Barang Masuk");
        mnLaporanBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanBarangMasukActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLaporanBarangMasuk);

        mnLaporanBarangKeluar.setText("Laporan Barang Keluar");
        mnLaporanBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLaporanBarangKeluarActionPerformed(evt);
            }
        });
        mnLaporan.add(mnLaporanBarangKeluar);

        jMenuBar1.add(mnLaporan);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoginActionPerformed
        new FLogin(this, false).setVisible(true);
    }//GEN-LAST:event_mnLoginActionPerformed

    private void mnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLogoutActionPerformed
        this.logout();

        JOptionPane.showMessageDialog(this, "Logout Berhasil",
                "Sukses", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnLogoutActionPerformed

    private void mnLaporanBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanBarangMasukActionPerformed
        new FLaporanBarangMasuk(this, false).setVisible(true);
    }//GEN-LAST:event_mnLaporanBarangMasukActionPerformed

    private void mnBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangActionPerformed
        new FBarang().setVisible(true);
    }//GEN-LAST:event_mnBarangActionPerformed

    private void mnSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSupplierActionPerformed
        new FSupplier().setVisible(true);
    }//GEN-LAST:event_mnSupplierActionPerformed

    private void mnBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangMasukActionPerformed
        new FBarangMasuk().setVisible(true);
    }//GEN-LAST:event_mnBarangMasukActionPerformed

    private void mnBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBarangKeluarActionPerformed
        new FBarangKeluar().setVisible(true);
    }//GEN-LAST:event_mnBarangKeluarActionPerformed

    private void mnLaporanBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLaporanBarangKeluarActionPerformed
        new FLaporanBarangKeluar(this, false).setVisible(true);
    }//GEN-LAST:event_mnLaporanBarangKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMenuUtama().setVisible(true);
            }
        });
    }

    public final void login() {
        initComponents();
        this.mnUser.setEnabled(true);
        this.mnManajemenBarang.setEnabled(true);
        this.mnPengadaan.setEnabled(true);
        this.mnLaporan.setEnabled(true);
        this.mnLogout.setEnabled(true);
        this.mnLogin.setEnabled(false);
    }

    public final void logout() {
        initComponents();
        this.mnUser.setEnabled(true);
        this.mnManajemenBarang.setEnabled(false);
        this.mnPengadaan.setEnabled(false);
        this.mnLaporan.setEnabled(false);
        this.mnLogout.setEnabled(false);
        this.mnLogin.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnBarang;
    private javax.swing.JMenuItem mnBarangKeluar;
    private javax.swing.JMenuItem mnBarangMasuk;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenu mnLaporan;
    private javax.swing.JMenuItem mnLaporanBarangKeluar;
    private javax.swing.JMenuItem mnLaporanBarangMasuk;
    private javax.swing.JMenuItem mnLogin;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenu mnManajemenBarang;
    private javax.swing.JMenu mnPengadaan;
    private javax.swing.JMenuItem mnSupplier;
    private javax.swing.JMenu mnUser;
    // End of variables declaration//GEN-END:variables
}
