/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import database.InventoryDB;

/**
 *
 * @author indak
 */
public class FSupplier extends javax.swing.JFrame {

    private Connection conn;
    private ResultSet rs;
    DefaultTableModel model = new DefaultTableModel();
    InventoryDB ks = new InventoryDB();

    /**
     * Creates new form FormMhs
     */
    public FSupplier() {
        initComponents();
        model = new DefaultTableModel();
        tblSupplier.setModel(model);
        model.addColumn("Kode Supplier");
        model.addColumn("Nama");
        loadDatabase();
        bersih();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKodeSupplier = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Master Supplier");

        jLabel2.setText("Kode Supplier");

        txtKodeSupplier.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtKodeSupplierCaretUpdate(evt);
            }
        });

        jLabel3.setText("Nama Supplier");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNamaSupplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(txtKodeSupplier, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(btnHapus))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(172, 172, 172)
                                .addComponent(btnTutup))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnTutup)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        int row = tblSupplier.getSelectedRow();

        if (row != -1) {
            try {
                String code = tblSupplier.getValueAt(row, 0).toString(); // Retrieve the supplier code from the first column (index 0)
                String name = tblSupplier.getValueAt(row, 1).toString(); // Retrieve the supplier name from the second column (index 1)

                // Set values to UI components based on the retrieved data
                txtKodeSupplier.setText(code);
                txtNamaSupplier.setText(name);

                JOptionPane.showMessageDialog(this, "Data berhasil ditampilkan");
            } catch (Exception e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(this, "Gagal menampilkan data");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih baris terlebih dahulu");
        }
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String code = this.txtKodeSupplier.getText();

        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data dengan kode " + code + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection c = InventoryDB.getKoneksi();
                String sql = "DELETE FROM suppliers WHERE code = ?";

                PreparedStatement p = c.prepareStatement(sql);
                p.setString(1, code);
                p.executeUpdate();
                p.close();

                JOptionPane.showMessageDialog(this, "Berhasil menghapus data dengan kode " + code);
            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(this, "Gagal menghapus data");
            } finally {
                loadDatabase();
                bersih();
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String code = this.txtKodeSupplier.getText(); // Gets the value from the JTextField for the supplier code
        String name = this.txtNamaSupplier.getText(); // Gets the value from the JTextField for the supplier name

        if (code.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kode supplier dan nama supplier wajib diisi");
        } else {
            try {
                Connection c = InventoryDB.getKoneksi();
                String checkIfExistsQuery = "SELECT COUNT(*) FROM suppliers WHERE code = ?";
                PreparedStatement checkIfExistsStmt = c.prepareStatement(checkIfExistsQuery);
                checkIfExistsStmt.setString(1, code);
                ResultSet rs = checkIfExistsStmt.executeQuery();

                if (rs.next() && rs.getInt(1) > 0) {
                    int confirmUpdate = JOptionPane.showConfirmDialog(this, "Apakah Anda ingin melakukan update supplier dengan kode " + code + "?", "Konfirmasi Update", JOptionPane.YES_NO_OPTION);

                    if (confirmUpdate == JOptionPane.YES_OPTION) {
                        // If the user confirms the update, perform the update operation
                        String updateQuery = "UPDATE suppliers SET name = ? WHERE code = ?";
                        PreparedStatement updateStmt = c.prepareStatement(updateQuery);
                        updateStmt.setString(1, name);
                        updateStmt.setString(2, code);
                        updateStmt.executeUpdate();

                        JOptionPane.showMessageDialog(this, "Berhasil diubah");
                    } else {
                        JOptionPane.showMessageDialog(this, "Update dibatalkan");
                    }
                } else {
                    // If the supplier code does not yet exist, perform an insert operation
                    String insertQuery = "INSERT INTO suppliers (code, name) VALUES (?, ?)";
                    PreparedStatement insertStmt = c.prepareStatement(insertQuery);
                    insertStmt.setString(1, code);
                    insertStmt.setString(2, name);
                    insertStmt.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Berhasil ditambahkan");
                }

                // Clean and update the display
                loadDatabase();
                bersih();
            } catch (SQLException e) {
                System.err.println(e);
                JOptionPane.showMessageDialog(this, "Gagal");
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtKodeSupplierCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtKodeSupplierCaretUpdate
        try {
            Connection c = InventoryDB.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM suppliers WHERE code = '" + this.txtKodeSupplier.getText() + "'";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                this.txtNamaSupplier.setText(r.getString("name"));
                // If there are date_created and date_updated columns in the suppliers table:
                // this.txtDateCreated.setText(r.getTimestamp("created_at").toString());
                // this.txtDateUpdated.setText(r.getTimestamp("updated_at").toString());
            }

            r.close();
            s.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_txtKodeSupplierCaretUpdate

    public void loadDatabase() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            Connection c = InventoryDB.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM suppliers";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                Object[] o = new Object[4];
                o[0] = r.getString("code");
                o[1] = r.getString("name");
                model.addRow(o);
            }

            r.close();
            s.close();
        } catch (SQLException e) {
            System.err.println(e);
        }
    }

    public void bersih() {
        txtKodeSupplier.requestFocus();
        txtKodeSupplier.setText("");
        txtNamaSupplier.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtKodeSupplier;
    private javax.swing.JTextField txtNamaSupplier;
    // End of variables declaration//GEN-END:variables
}
